tooltip<-function(session)
{
  addPopover(session,'clusters',title=NULL,content = 'Set the no. of parallel clusters to be used', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'format',title=NULL,content = 'Select between given file formats. File upload limit is 8000mb.It is recommended to upload large datasets in .RData format', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'impute',title=NULL,content = 'Impute missing data', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'dtype',title=NULL,content = 'Choose data discretization algorithm (Hybrid is recommended)', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'discretize',title=NULL,content = 'Discretize continous variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'transpose',title=NULL,content = 'Switch rows and columns', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'sort',title=NULL,content = 'Sort columns in alphebetical order', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'delSelect',title=NULL,content = 'Select variables to delete', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'reset',title=NULL,content = 'Undo delete', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'downloadDataset',title=NULL,content = 'Download data in .CSV format', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'freqSelect',title=NULL,content = 'Select varibale to observe distribution', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'tableName',title=NULL,content = 'Table available for exporting', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'downloadData',title=NULL,content = 'Download selected table', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'assocType',title=NULL,content = "Metric for association strength (cramer's V is recommended)", placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'association',title=NULL,content = 'Build association graph', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'threshold',title=NULL,content = 'Set threshold for edges to keep. All edges below the threshold will be removed', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Avarselect',title=NULL,content = 'Select variables to group', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Avarshape',title=NULL,content = 'select shape of the grouped variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Agroup',title=NULL,content = 'group selected variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Avarselectvector',title=NULL,content = 'vector of variable indices to group', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Avarshape2',title=NULL,content = 'select shape of grouped variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Avarshape3',title=NULL,content = 'select shape of grouped variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Agroup2',title=NULL,content = 'group selected variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Adegree',title=NULL,content = 'Only neighbors upto Nth degree will be visible', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'AdegreeN',title=NULL,content = 'Degree of neighbors to display', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Agraph_layout',title=NULL,content = 'select layout for the graph', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'Aneighbornodes',title=NULL,content = 'list of Nth neighbors', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'paramMethod',title=NULL,content = 'select parameter learning algorithm (Bayesian estimation is recommended)', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'structFile',title=NULL,content = 'Upload already learned bayesian structure', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'bootFile',title=NULL,content = 'Upload already learned bootsraped bayesian structure', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'edgeStrengthU',title=NULL,content = 'Edges with strength less than the threshold will be removed', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'directionStrengthU',title=NULL,content = 'Edges with direction confidence less than the threshold will be removed', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'parameterTuningU',title=NULL,content = 'Tweak the learnt network', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'boot',title=NULL,content = 'No. of bootstrap iterations', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'SampleSize',title=NULL,content = 'sample size for bootstrap learning', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'edgeStrength',title=NULL,content = 'Edges with strength less than the threshold will be removed', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'directionStrength',title=NULL,content = 'Edges with direction confidence less than the threshold will be removed', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'learnBtn',title=NULL,content = 'Do a boostrapped structure learning(Recommended)', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'learnSBtn',title=NULL,content = 'Do a one-time structure learning', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'GNNGraphButton',title=NULL,content = 'Please Ensure you are running this method on a CUDA enabled machine', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'PruneBtn',title=NULL,content = 'Tweak the learnt network', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'paramMethod2',title=NULL,content = 'select parameter learning algorithm (Bayesian estimation is recommended)', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'saveBtn',title=NULL,content = 'Download learnt struture', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'lossFunc',title=NULL,content = 'prediction algorithm for individual variable error evaluation', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'paramMethod3',title=NULL,content = 'select parameter learning method used on learnt structure', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'scoreAlgo',title=NULL,content = 'Network score calculation algorithm(mbde is recommended)', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'getScore',title=NULL,content = 'Get network score', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'insertBtn',title=NULL,content = 'Insert evidence node', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'removeBtn',title=NULL,content = 'Remove evidence node', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'event',title=NULL,content = 'select event node', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'varselect',title=NULL,content = 'Select variables to group', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'varshape',title=NULL,content = 'select shape of the grouped variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'group',title=NULL,content = 'group selected variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'varselectvector',title=NULL,content = 'vector of variable indices to group', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'varshape2',title=NULL,content = 'select shape of grouped variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'group2',title=NULL,content = 'group selected variables', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'degree',title=NULL,content = 'Only neighbors upto Nth degree will be visible', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'degreeN',title=NULL,content = 'Degree of neighbors to display', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'graph_layout',title=NULL,content = 'select layout for the graph', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'neighbornodes',title=NULL,content = 'list of Nth neighbors', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'AmoduleSelection',title=NULL,content = 'select between graph and learned modules', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'AmoduleAlgo',title=NULL,content = 'select clustering algorithm for module detection (Ward.D is recommended)', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'moduleSelection',title=NULL,content = 'select between graph and learned modules', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'moduleAlgo',title=NULL,content = 'select clustering algorithm for module detection (Ward.D is recommended)', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'plotBtn',title=NULL,content = 'build a without error bars plot', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'plotStrengthBtn',title=NULL,content = 'build plot with error bars', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'numInterval',title=NULL,content = 'no. of iterations for confidence plot. Must be numeric value', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'NumBar',title=NULL,content = 'No. of bars on the plot', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'sortPlot',title=NULL,content = 'sort the plot by X-axis', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'paramSelect',title=NULL,content = 'select variable to visualize local conditional probability distribution', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'dashboard',title=NULL,content = 'Download dashboard for publishing your results', placement = "top", trigger = "hover",options = NULL)
  addPopover(session,'name',title=NULL,content = 'Name your dashboard', placement = "top", trigger = "hover",options = NULL)
}
