dependency<-function()
{
  if (!requireNamespace("BiocManager"))
    install.packages("BiocManager")
  if(require('graph')==F)
  {
    BiocManager::install('graph')
  }
  if(require('igraph')==F)
  {
    install.packages('igraph')
  }
  if(require('RBGL')==F)
  {
    BiocManager::install('RBGL')
  }
  if(require('Rgraphviz')==F)
  {
    BiocManager::install('Rgraphviz')
  }
  if(require('gRbase')==F)
  {
    install.packages('gRbase')
  }
  if(require('gRain')==F)
  {
    install.packages('gRain')
  }
  if(!"RCy3" %in% installed.packages()){
    BiocManager::install("RCy3")
  }
  library(RCy3)
}
